FROM nvidia/cuda:12.6.3-base-ubuntu24.04

ARG PROXY=""
ENV all_proxy=${PROXY}

COPY --from=ghcr.io/astral-sh/uv:0.6.12 /uv /uvx /bin/
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync
# https://docs.astral.sh/uv/guides/integration/pytorch/#automatic-backend-selection
RUN uv pip install torch torchaudio torchvision --torch-backend=cu126 --preview

CMD ["uv", "run", "main.py"]
