# B站用户的SESSDATA，用于API认证
SESSDATA: "Cookie里的SESSDATA字段值"

# 原始历史记录数据的输入文件夹
input_folder: "history_by_date"

# 清理后的历史记录数据的输出文件夹
output_folder: "output"

# SQLite数据库文件名
db_file: "bilibili_history.db"

# 导入日志文件名，用于记录上次导入的位置
log_file: "last_import_log.json"

# 分类配置文件名
categories_file: "categories.json"

# 每日观看数量统计文件夹
daily_count_folder: "daily_count"

# 热力图模板文件名
heatmap_template: "template.html"

# 清理数据时需要移除的字段列表
fields_to_remove:
  - long_title    # 长标题
  - uri           # 统一资源标识符
  - badge         # 徽章
  - current       # 当前状态
  - total         # 总数
  - new_desc      # 新描述
  - is_finish     # 是否完成
  - live_status   # 直播状态

# 邮件配置
email:
  smtp_server: smtp.qq.com
  smtp_port: 587
  sender: "xxxx@qq.com"
  password: "xxxx"  # QQ邮箱授权码
  receiver: "xxxx@qq.com"

# 日志文件夹
log_folder: "/www/wwwroot/python/logs"

# yutto 下载器配置
yutto:
  basic:
    # 设置下载目录
    dir: "./output/download_video"
    # 设置临时文件目录
    tmp_dir: "./output/tmp_video"
    # 设置大会员严格校验
    vip_strict: false
    # 设置登录严格校验
    login_strict: false
  
  resource:
    # 不下载字幕
    require_subtitle: false
  
  danmaku:
    # 设置弹幕字体大小
    font_size: 30
    # 设置弹幕屏蔽关键词
    block_keyword_patterns: []
  
  batch:
    # 下载额外剧集
    with_section: true

# 服务器配置
server:
  host: "localhost"
  port: 8899  # 设置你想要的端口号

# 热力图配置
heatmap:
  # 热力图输出目录
  output_dir: ""
  # 热力图模板文件
  template_file: "template.html"
  # 热力图标题
  title: "Bilibili 每年每日视频观看热力图"
  # 图表尺寸配置
  chart:
    width: "1000px"
    height: "200px"
  # 热力图颜色配置
  colors:
    pieces:
      - min: 1
        max: 10
        color: "#FFECF1"
      - min: 11
        max: 50
        color: "#FFB3CA"
      - min: 51
        max: 100
        color: "#FF8CB0"
      - min: 101
        max: 200
        color: "#FF6699"
      - min: 201
        max: 9999
        color: "#E84B85"

# 在配置文件中添加任务超时设置
scheduler:
  task_timeout: 600  # 任务超时时间（秒）
  retry_delay: 300   # 重试延迟时间（秒）
  max_retries: 3     # 最大重试次数