base_url: http://localhost:8899
tasks:
  fetch_history:
    name: 获取B站历史记录
    endpoint: /fetch/bili-history
    method: GET
    schedule:
      type: daily
      time: 00:00
    requires: []
    params: {}
  import_data:
    name: 导入数据到数据库
    endpoint: /importSqlite/import_data_sqlite
    method: POST
    schedule:
      type: chain
    requires:
    - fetch_history
  analyze_data:
    name: 分析历史数据
    endpoint: /analysis/analyze
    method: POST
    schedule:
      type: chain
    requires:
    - import_data
  generate_heatmap:
    name: 生成观看热力图
    endpoint: /heatmap/generate_heatmap
    method: POST
    schedule:
      type: chain
    requires:
    - analyze_data
  send_daily_report:
    name: 发送每日报告
    endpoint: /log/send-email
    method: POST
    params:
      subject: B站历史记录日报 - {current_time}
      content: null
      mode: simple
    schedule:
      type: chain
    requires:
    - generate_heatmap
scheduler:
  log_level: INFO
  retry:
    max_attempts: 3
    delay: 60
error_handling:
  stop_on_failure: true
  notify_on_failure: true
